version: '3'

services:
  api:
    container_name: api
    build: ./api
    volumes:
      - ./api
    ports: 
      - 3000:3000
  
  app:
    container_name: app
    build: ./app
    volumes:
      - ./app/pages:/usr/src/app/pages
      - ./app/nuxt.config.js:/usr/src/app/nuxt.config.js
    ports:
      - 8000:8000
    depends_on:
      - api

  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - "api"
      - "app"