version: '3'

services:
  api:
    container_name: api
    build: ./api
    volumes:
      - ./api
    ports: 
      - 3000:3000

  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - "api"